### ISSUE TITLE
Very minor: Php Warning line 24

### ISSUE THREAD

**Issue by shines** [strangerstudios/pmpro-cpt#1]
Howdy,

If you don't have a redirect enabled for your CPT, yet wish to use the metabox, you get a php undefined index for line 24. Doesn't hurt much, but I try to remove them for cleaner troubleshooting. Here's the fix if you want it!

```
$redirect_to = isset($options['redirect_to'][0]) ? intval($options['redirect_to'][0]) : '';
```

Best,
Sarah

**Comment by strangerstudios** [comment]
Thanks! Finally got around to fixing this in the .2 commit just done now: https://github.com/strangerstudios/pmpro-cpt/commit/4f666a6186492fe8c775dc66dcfadc4c115b2608
