### ISSUE TITLE
Feature Request: Allow users to choose which CPTs are redirected away from vs filtered

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-cpt#11]
The PMPro CPT add on redirects non-members away from member content because we can't be sure how a CPT is displayed and if our basic the_content filter will properly protect the member content.

However, sometimes you know the content will be protected enough and would rather have the content filter and links to checkout/etc like we do for posts and pages by default.

This code disables the redirect entirely: https://gist.github.com/ideadude/76872d4ee982f7add05dafb69cf00d13

We could perhaps add a filter to the redirect code to disable it for specific CPTs.

We could then also consider adding UI to the settings to select some CPTs to redirect away from entirely and some to just filter. That probably needs a lot of thought because the concept is pretty hard to get I think. I'd like a solution that is not too complicated for users to manage and understand what is happening.

**Comment by JarrydLong** [comment]
Just leaving a note here that while testing version 1.0, there is a filter that can be used to determine which CPT is being redirected `apply_filters( 'pmprocpt_redirect_to', $redirect_to, $selected_cpts, $options )` and decide to redirect or not from there.
