### ISSUE TITLE
Add support for custom taxonomies

### ISSUE THREAD

**Issue by curious-toad** [strangerstudios/pmpro-cpt#16]
Hi there,

Is it possible to adapt pmprocpt_getCPTs to search for custom taxonomy as well as CPTs?

Cheers

Rob

**Comment by JarrydLong** [comment]
I don't forsee us adding something like this in. Instead, please refer to this article (https://www.paidmembershipspro.com/restrict-by-taxonomy/) which makes use of a code recipe to protect content in a specific taxonomy.
