### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by stefwilliams** [strangerstudios/pmpro-cpt#2]
Just spotted that if I select a CPT to restrict access to, then save settings, then deselect all CPTs and save settings again, when I hit the front end, I get:

Fatal error: Cannot use string offset as an array in [...]/wp-content/plugins/pmpro-cpt/pmpro-cpt.php on line 24

Easy enough to work around, by selecting any CPT in the backend again, but could be a bit worrying for people.
(Unless my theme has somehow caused this - I haven't got any others installed atm so haven't checked.)

**Comment by strangerstudios** [comment]
You posted this forever ago, but I'm not able to recreate this anymore. Maybe we fixed it, maybe there is something else going on. Let me know if you're still seeing this behavior. Thanks.
