### ISSUE TITLE
Error on PHP 8.0+

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-cpt#21]
**Describe the bug**
A customer ran into an error on PHP 8.0+.

**To Reproduce**
1. Set PHP version to PHP 8.0+
2. Activate Paid Memberships Pro, and Custom Post Type Add On. See this error:

```
Error Details
=============
An error of type E_ERROR was caused in line 194 of the file /nas/content/live/wp-content/plugins/pmpro-cpt/pmpro-cpt.php. Error message: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given in /nas/content/live/wp-content/plugins/pmpro-cpt/pmpro-cpt.php:194
Stack trace:
#0 /nas/content/live/wp-content/plugins/pmpro-cpt/pmpro-cpt.php(194): trim(Array)
#1 /nas/content/live/wp-includes/class-wp-hook.php(310): pmprocpt_options_validate(Array)
#2 /nas/content/live/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#3 /nas/content/live/wp-includes/formatting.php(5000): apply_filters(‘sanitize_option…’, Array, ‘pmprocpt_option…’, Array)
#4 /nas/content/live/wp-includes/option.php(638): sanitize_option(‘pmprocpt_option…’, Array)
#5 /nas/content/live/wp-includes/option.php(496): add_option(‘pmprocpt_option…’, Array, ”, ‘yes’)
#6 /nas/content/live/wp-admin/options.php(322): update_option(‘pmprocpt_option…’, Array)
#7 {main}
thrown
```

**Expected behavior**
There should not be an error.

**Isolating the problem:**
- [x] Deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro 2.9.12, and Custom Post Type Add On 1.0 is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).

This came up in ticket 465372 on PHP 8.0.26, and this error happened in my test with PHP 8.0.22.

**WordPress Environment**
<details> 
Paid Memberships Pro 2.9.12, and Custom Post Type Add On 1.0, WordPress 6.1.1, PHP 8.0.22
</details>

**Comment by ipokkel** [comment]
This also came up in ticket 495117 while running PHP 8.0.27

**Comment by michaelbeil** [comment]
Another customer (ticket 503241) reported this.
